### ISSUE TITLE
Error on process task string

### ISSUE THREAD

**Issue by geaaru** [MottainaiCI/mottainai-cli#7]
Task is not create if I drop at begin and end double-quote.

https://github.com/Sabayon/sbi-tasks/blob/master/iso/spinbase/monitor-spinbase.yaml#L27

```
mottainai-cli task create --yaml monitor-spinbase.yaml 
panic: error unmarshaling JSON: json: cannot unmarshal object into Go struct field Task.script of type string

goroutine 1 [running]:
github.com/MottainaiCI/mottainai-cli/cmd/task.newTaskCreateCommand.func1(0xc420262f00, 0xc4201ec840, 0x0, 0x4)
	/home/geaaru/go/src/github.com/MottainaiCI/mottainai-cli/cmd/task/create.go:74 +0xeb9
github.com/MottainaiCI/mottainai-cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc420262f00, 0xc4201ec800, 0x4, 0x4, 0xc420262f00, 0xc4201ec800)
	/home/geaaru/go/src/github.com/MottainaiCI/mottainai-cli/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/MottainaiCI/mottainai-cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x141a620, 0x1, 0x2, 0x1e)
	/home/geaaru/go/src/github.com/MottainaiCI/mottainai-cli/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/MottainaiCI/mottainai-cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x141a620, 0x1e, 0xbd8000)
	/home/geaaru/go/src/github.com/MottainaiCI/mottainai-cli/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/MottainaiCI/mottainai-cli/cmd.Execute()
	/home/geaaru/go/src/github.com/MottainaiCI/mottainai-cli/cmd/root.go:148 +0x2d
main.main()
	/home/geaaru/go/src/github.com/MottainaiCI/mottainai-cli/mottainai-cli.go:53 +0x209

```

**Comment by geaaru** [comment]
This is related with an issue with yaml parser library used by Mottainai.

A similar issue is present with task compilation where a field like this:

````
name: "my task name: {{ .var }}"
````
is then converted in
```
name: my task name: myvar
```
that then generate error on parsing.
