### ISSUE TITLE
Fix creation of profiles config when config directory is not present

### ISSUE THREAD

**Issue by geaaru** [MottainaiCI/mottainai-cli#9]
```
panic: mkdir /root/.config/mottainai: no such file or directory
goroutine 1 [running]:
github.com/MottainaiCI/mottainai-cli/common.CheckError(...)
	/var/tmp/portage/dev-util/mottainai-cli-0.0_pre20181231/work/mottainai-cli-0.0_pre20181231/src/github.com/MottainaiCI/mottainai-cli/common/tools.go:38
github.com/MottainaiCI/mottainai-cli/cmd/profile.newProfileCreateCommand.func1(0xc0005f9400, 0xc00052be00, 0x3, 0x3)
	/var/tmp/portage/dev-util/mottainai-cli-0.0_pre20181231/work/mottainai-cli-0.0_pre20181231/src/github.com/MottainaiCI/mottainai-cli/cmd/profile/create.go:95 +0xc3f
github.com/MottainaiCI/mottainai-cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc0005f9400, 0xc00052bb00, 0x3, 0x3, 0xc0005f9400, 0xc00052bb00)
	/var/tmp/portage/dev-util/mottainai-cli-0.0_pre20181231/work/mottainai-cli-0.0_pre20181231/src/github.com/MottainaiCI/mottainai-cli/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/MottainaiCI/mottainai-cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000b8c80, 0xc00067e780, 0xc00067f400, 0xc000672280)
	/var/tmp/portage/dev-util/mottainai-cli-0.0_pre20181231/work/mottainai-cli-0.0_pre20181231/src/github.com/MottainaiCI/mottainai-cli/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/MottainaiCI/mottainai-cli/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0000b8c80, 0xc0000f1680, 0xc0007f7f88)
	/var/tmp/portage/dev-util/mottainai-cli-0.0_pre20181231/work/mottainai-cli-0.0_pre20181231/src/github.com/MottainaiCI/mottainai-cli/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/MottainaiCI/mottainai-cli/cmd.Execute()
	/var/tmp/portage/dev-util/mottainai-cli-0.0_pre20181231/work/mottainai-cli-0.0_pre20181231/src/github.com/MottainaiCI/mottainai-cli/cmd/root.go:177 +0x15c
main.main()
	/var/tmp/portage/dev-util/mottainai-cli-0.0_pre20181231/work/mottainai-cli-0.0_pre20181231/src/github.com/MottainaiCI/mottainai-cli/mottainai-cli.go:26 +0x20
```

**Comment by geaaru** [comment]
Fixed with 01190b1ca8b45187b31fb32ef638bb727a70c1c3
